name: Build, Lint and Publish

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - developer
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  # Run tests for any PRs.
  pull_request:
jobs:  
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  lint:
    # Ensure test job passes before pushing image.
    runs-on: automate
    steps:
      - uses: AutoModality/action-clean@v1
      - uses: actions/checkout@v2

  build:
    needs: lint
    # Ensure test job passes before pushing image.
    runs-on: automate
    steps:
      - uses: actions/checkout@v2
      - name: Fetch Deployment files
        run: |
            export VAULT_TOKEN="${{ secrets.VaultToken }}" && vault kv get -address="https://vault.sirpi.co.in" -field=config kv/devops/kubernetes > config
            git clone git@github.com/bhupendra-sirpi/test-dev.git
            docker build -t test .
            kubectl create pod test --image=test
